#!/usr/bin/env bash

if [[ $OSTYPE == 'linux'* ]]; then
sudo apt update
sudo apt install -y \
	gcc \
	make \
	cmake \
	git \
	build-essential \
	gdb \
	unzip \
	ripgrep \
	fd-find \
	curl \
	wget \
	fzf \
	htop \
	rofi \
	manpages \
	iftop \
	bmon \
	tldr \
elif [[ "$OSTYPE" == 'darwin'* ]]; then
	brew install --cask mos
fi
