#!/usr/bin/env bash

sudo apt update
sudo apt install -y \
	gcc \
	make \
	cmake \
	git \
	build-essential \
	gdb \
	unzip \
	ripgrep \
	fd-find \
	curl \
	wget \
	exa \
	fzf \
	htop \
	rofi \
	manpages \
	iftop \
	bmon \
	tldr \
