#!/usr/bin/env bash

git clone https://github.com/ghostty-org/ghostty $HOME/personal/ghostty
cd $HOME/personal/ghostty

git checkout v1.1.3 

sudo apt install libgtk-4-dev libadwaita-1-dev git blueprint-compiler gettext libxml2-utils
zig build -Doptimize=ReleaseFast

