#!/usr/bin/env bash


if [[ $OSTYPE == 'linux'* ]]; then
	sudo apt update
	sudo apt install -y ninja-build gettext cmake curl wget build-essential luarocks
elif [[ "$OSTYPE" == 'darwin'* ]]; then
	xcode-select --install
	brew install ninja cmake gettext curl wget luarocks
fi

# delete previous installation
sudo rm /usr/local/bin/nvim
sudo rm -r /usr/local/share/nvim

TMP_DIR=$(mktemp -d)

cd "$TMP_DIR"
git clone https://github.com/neovim/neovim
cd neovim
git checkout stable
make CMAKE_BUILD_TYPE=RelWithDebInfo

sudo make install
