#!/usr/bin/env bash

sudo apt update
sudo apt install ninja-build gettext cmake curl build-essential

# delete previous installation
sudo rm /usr/local/bin/nvim
sudo rm -r /usr/local/share/nvim

TMP_DIR=$(mktemp -d)

cd "$TMP_DIR"
git clone https://github.com/neovim/neovim
cd neovim
git checkout stable
make CMAKE_BUILD_TYPE=RelWithDebInfo

sudo make install
