#!/usr/bin/env bash


if [[ "$OSTYPE" == 'linux'* ]]; then
	sudo apt update
	sudo apt install -y fzf tmux
elif [[ "$OSTYPE" == 'darwin'* ]]; then
	brew install fzf tmux 
fi

TMP_DIR=$(mktemp -d)

cd "$TMP_DIR"
git clone https://github.com/ThePrimeagen/tmux-sessionizer
cd tmux-sessionizer
mkdir -p $HOME/.local/bin
mv tmux-sessionizer $HOME/.local/bin/

# Cleanup
rm -rf "$TMP_DIR"
