#!/usr/bin/env bash

sudo apt update
sudo apt install -y fzf tmux

TMP_DIR=$(mktemp -d)

cd "$TMP_DIR"
git clone https://github.com/ThePrimeagen/tmux-sessionizer
cd tmux-sessionizer
mv tmux-sessionizer $HOME/.local/bin

