#!/usr/bin/env bash

TMP_DIR=$(mktemp -d)

# Remove previous installation
rm -rf $HOME/.local/bin/zen-browser
rm $HOME/.local/bin/zen
sudo rm /usr/share/applications/zen.desktop

cd "$TMP_DIR"
wget https://github.com/zen-browser/desktop/releases/latest/download/zen.linux-x86_64.tar.xz
tar -xf zen.linux-x86_64.tar.xz
mv zen/ $HOME/.local/bin/zen-browser
ln -s $HOME/.local/bin/zen-browser/zen $HOME/.local/bin/zen

# Create .desktop file
sudo mkdir -p /usr/share/applications
echo "[Desktop Entry]
Version=1.0
Name=Zen Browser
Comment=Experience tranquillity while browsing the web without people tracking you!
GenericName=Web Browser
Keywords=Internet;WWW;Browser;Web;Explorer
Exec=$HOME/.local/bin/zen
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/usr/share/icons/Papirus/48x48/apps/zen-browser.svg
Categories=GNOME;GTK;Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
StartupNotify=true" | sudo tee /usr/share/applications/zen.desktop

# Cleanup
sudo rm -rf "$TMP_DIR"
