#!/usr/bin/env bash

if [[ $OSTYPE == 'linux'* ]]; then
	sudo apt update
	sudo apt install -y zsh zplug
	# Make zsh the default shell
	chsh -s /bin/zsh
elif [[ "$OSTYPE" == 'darwin'* ]]; then
	brew install zsh zplug
	chsh -s $(which zsh)
fi


# oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
